### PR TITLE
Leave IP out of ENR by default

### LINKED ISSUE #286: test_response_to_triple_ack local test failure
Repeatable test failure (3 of 3 attempts on a fresh checkout of master at c00e99c6b

CI appears green at the commit, so I'm guessing it's some kind of configuration issue. I just added here for tracking (and also a reminder to add a README section about running the local test).

Captured output:
```
$ TRIN_INFURA_PROJECT_ID=1 RUST_LOG=debug cargo test -p trin-core
    Finished test [unoptimized + debuginfo] target(s) in 0.17s
     Running unittests (target/debug/deps/trin_core-19ec7be1499b1d43)

running 127 tests
test cli::test::test_custom_discovery_port ... ok
✂️ ✂️ ✂️ 
test portalnet::types::content_key::test::test_distance_to_key ... ok
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up RocksDB at path: "/tmp/trin.8RiPOGjQik5o/rocksdb"
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up SqliteDB at path: "/tmp/trin.8RiPOGjQik5o/trin.sqlite"
[2022-03-31T22:40:03Z DEBUG discv5::discv5] Discv5 service already shutdown
[2022-03-31T22:40:03Z DEBUG discv5::discv5] Discv5 service already shutdown
test utp::stream::tests::test_response_to_triple_ack ... FAILED
test portalnet::types::content_key::test::test_should_store ... ok
[2022-03-31T22:40:03Z INFO  trin_core::portalnet::discovery] Starting discv5 with local enr encoded=enr:-IS4QJIjtY6mIYt5tnOIa89gnMsZu76Bd5Bg45gMaUKJW-RoAHq6nMg0r4G4APtTTduRlnekuWgp9QKyZKnIt78zBfsBgmlkgnY0gmlwhMCoAcCJc2VjcDI1NmsxoQJ9TpUJQOxBIiqmFdLWSXi81LLm9HrWkpwH_JTIaQuhU4N1ZHCCEJI decoded=ENR: NodeId: 0x5b61..bb5f, Socket: Some(192.168.1.192:4242)
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up RocksDB at path: "/tmp/trin.8RiPOGjQik5o/rocksdb"
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up SqliteDB at path: "/tmp/trin.8RiPOGjQik5o/trin.sqlite"
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::overlay_service] [History] Sending Ping request to node. Node: 0x08d3..fb5a
[2022-03-31T22:40:03Z DEBUG discv5::discv5] Service is already shutdown
test portalnet::overlay_service::tests::ping_node ... ok

failures:

---- utp::stream::tests::test_response_to_triple_ack stdout ----
thread 'utp::stream::tests::test_response_to_triple_ack' panicked at 'called `Result::unwrap()` on an `Err` value: Discv5 socket timeout', trin-core/src/utp/stream.rs:1623:37


failures:
    utp::stream::tests::test_response_to_triple_ack

test result: FAILED. 126 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.24s
```

### PR DESCRIPTION
**Pull request by carver**
An alternative fix #286

This fits with the discv5 validation, which hangs up on clients
immediately if the ENR IP does not match the observed IP.

Also, had to update a couple tests to configure local IPs so they can
contact each other. (The internal IP feature randomly chose a local
IP, which caused the discv5 validation to reject the local connections)

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [x] Clean up commit history

### CODE REVIEW

File: trin-core/src/portalnet/discovery.rs [hunk 1]
```diff
@@ -30,7 +30,7 @@ pub struct Config {
 impl Default for Config {
     fn default() -> Self {
         Self {
-            listen_address: "0.0.0.0".parse().expect("valid ip address"),
+            listen_address: None,
```
Comment (njgheorghita) [inline trin-core/src/portalnet/discovery.rs:33]: change to `enr_address`

File: trin-core/src/portalnet/discovery.rs [hunk 2]
```diff
@@ -53,20 +53,24 @@ impl Discovery {
     pub fn new(portal_config: PortalnetConfig) -> Result<Self, String> {
         let listen_all_ips = SocketAddr::new("0.0.0.0".parse().unwrap(), portal_config.listen_port);
 
-        let ip_addr = if portal_config.internal_ip {
-            socket::default_local_address(portal_config.listen_port)
+        let (ip_addr, ip_port) = if portal_config.internal_ip {
```
Comment (njgheorghita) [inline trin-core/src/portalnet/discovery.rs:56]: `internal_ip` is no longer an appropriate name.... `blank_enr`? `skip_stun`?

File: trin-core/src/portalnet/discovery.rs [hunk 3]
```diff
@@ -53,20 +53,24 @@ impl Discovery {
...
+            (None, portal_config.listen_port)
         } else {
-            portal_config
+            let known_external = portal_config
```
Comment (njgheorghita) [inline trin-core/src/portalnet/discovery.rs:59]: in `cli.rs` restrict arguments to only `--internal-ip` or `--external-address ...`

**Review by njgheorghita — APPROVED** [review]
⛵
