### PR TITLE
fix: use default angelfood bootnodes if network is selected

### LINKED ISSUE #1460: Properly handle Bootnodes for Mainnet and Angelfood networks
Currently our test network `AngelFood` doesn't have default bootnodes. It would be ideal to have each network have it's own list of bootnodes. 

So when you boot trin with `--network angelfood`, and we use the default bootnodes option it uses bootnodes for angelfood instead of mainnet.

https://github.com/ethereum/portal-network-specs/blob/master/bootnodes.md bootnodes are list here. (currently the bootnode for angelfood isn't online)

### PR DESCRIPTION
**Pull request by njgheorghita**
### What was wrong?
fixes #1460

### How was it fixed?
Added angelfood bootnodes and logic to handle the correct bootnodes depending on what network's selected.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

### CODE REVIEW

**Review by KolbyML — APPROVED** [review]
:shipit: I think it is weird to be able to use `mainnet` bootnodes on `angelfood` or the inverse. But I definitely think this PR is an big improvement on what we currently have.

**Comment by morph-dev** [comment]
I also don't like that there is "angelfood" as an option. Somebody can just call `--bootnodes=angelfood` and since mainnet is default network, this would not really work in practice.

In my opinion, "default" bootnodes would depend on the Network.
The way it would work is that instead of having `impl From<Bootnodes> for Vec<Enr>`, we would have:

```rust
impl Bootnodes {
    pub fn to_enrs(&self, network: Network) -> Vec<Enr> {
        let bootnodes: &Vec<Bootnode> = match (self, network) {
            (Bootnodes::Default, Network::Mainnet) => &DEFAULT_BOOTNODES,
            (Bootnodes::Default, Network::Angelfood) => &ANGELFOOD_BOOTNODES,
            (Bootnodes::None, _) => &vec![],
            (Bootnodes::Custom(bootnodes), _) => &bootnodes,
        };
        bootnodes.iter().map(|bn| bn.enr.clone()).collect()
    }
}
```

This breaks the PortalnetConfig, which doesn't have access the the network. To solve that problem, we can either:
- change `PortalnetConfig.bootnodes` to be `Vec<Enr>`, as all uses that I found are like:
    `let bootnode_enrs: Vec<Enr> = portal_config.bootnodes.into();`
- add network field to `PortalnetConfig`

I personally might have slight preference towards the first one.

If I missed something and it's not so simple, feel free to merge it as it is now.

**Comment by KolbyML** [comment]
> I also don't like that there is "angelfood" as an option. Somebody can just call `--bootnodes=angelfood` and since mainnet is default network, this would not really work in practice.
> 
> In my opinion, "default" bootnodes would depend on the Network. The way it would work is that instead of having `impl From<Bootnodes> for Vec<Enr>`, we would have:
> 
> ```rust
> impl Bootnodes {
>     pub fn to_enrs(&self, network: Network) -> Vec<Enr> {
>         let bootnodes: &Vec<Bootnode> = match (self, network) {
>             (Bootnodes::Default, Network::Mainnet) => &DEFAULT_BOOTNODES,
>             (Bootnodes::Default, Network::Angelfood) => &ANGELFOOD_BOOTNODES,
>             (Bootnodes::None, _) => &vec![],
>             (Bootnodes::Custom(bootnodes), _) => &bootnodes,
>         };
>         bootnodes.iter().map(|bn| bn.enr.clone()).collect()
>     }
> }
> ```
> 
> This breaks the PortalnetConfig, which doesn't have access the the network. To solve that problem, we can either:
> 
> * change `PortalnetConfig.bootnodes` to be `Vec<Enr>`, as all uses that I found are like:
>   `let bootnode_enrs: Vec<Enr> = portal_config.bootnodes.into();`
> * add network field to `PortalnetConfig`
> 
> I personally might have slight preference towards the first one.
> 
> If I missed something and it's not so simple, feel free to merge it as it is now.

I really like this direction

**Comment by njgheorghita** [comment]
@morph-dev ready for another :eyes: here

File: ethportal-api/src/types/bootnodes.rs [hunk 1]
```diff
@@ -2,14 +2,32 @@ use std::str::FromStr;
...
 
 #[derive(Clone, Debug, Eq, PartialEq)]
 pub struct Bootnode {
     pub enr: Enr,
     pub alias: String,
 }
 
+impl From<Enr> for Bootnode {
+    fn from(enr: Enr) -> Self {
+        let all_bootnodes = DEFAULT_BOOTNODES
```
Comment (morph-dev) [inline ethportal-api/src/types/bootnodes.rs:15]: nit: I don't think you have to clone all DEFAULT_BOOTNODES and ANGELFOOD_BOOTNODES. You can iterate over references and clone only if you find match. Something like this:

```rust
Iterator::chain(DEFAULT_BOOTNODES.iter(), ANGELFOOD_BOOTNODES.iter())
    .find(|bootnode| bootnode.enr == enr)
    .cloned()
    .unwrap_or_else(|| Self {
        enr,
        alias: "custom".to_string(),
    })
```

File: portalnet/src/config.rs [hunk 2]
```diff
@@ -33,7 +35,7 @@ impl Default for PortalnetConfig {
             external_addr: None,
             private_key: B256::random(),
             listen_port: 4242,
-            bootnodes: Bootnodes::default(),
+            bootnodes: Bootnodes::default().to_enrs(Network::Mainnet),
```
Comment (morph-dev) [inline portalnet/src/config.rs:38]: nit: I don't like that `PortalnetConfig` implements `Default` that shouldn't be used in production code (there is a chance it can be used by mistake).
Currently it's used only in tests (as far as I can tell), so I would remove this and add something like this:

```rust
impl PortalnetConfig {
    pub fn new(trin_config: &TrinConfig, private_key: B256) -> Self {
        // current function
    }

    #[cfg(test)]
    pub fn new_for_tests() -> Self {
        Self {
            // current default
        }
    }
}
```

But, it isn't really a big deal and not really part of this PR, so feel free to ignore it (more of an idea of how we can do this better in general).
Up to you.

**Review by morph-dev — APPROVED** [review]
LGTM :ship: 

Left two, small and optional comments. Totally up to you.

File: portalnet/src/config.rs (hunk 2 above)
Comment (njgheorghita) [reply portalnet/src/config.rs:38]: Well, we do use the `Default` trait quite a bit...
- inside `PortalnetConfig::new()`
- in "test" utils that which don't seem to be scoped to the test compilation set (https://github.com/ethereum/trin/blob/master/utp-testing/src/lib.rs#L164)
- inside our unit tests 

Ultimately, the `Default` syntax is quite handy for initializing a new instance with only a few adjusted fields (https://github.com/ethereum/trin/blob/master/portalnet/src/overlay/service.rs#L2779)...

I get your concern about using it inside "production" code, so I removed it from the `PortalnetConfig::new()` constructor. 
- the only fields that were being set by the `Default` trait were...
  - `internal_ip` - which we actually never use, so I removed it
  - `node_addr_cache_capacity` - which I just updated to use the default value. Maybe this should be added as a cli arg?

And I added a comment to the `Default` trait that it should only be used inside testing (obvs. this won't be caught by the compiler)
