### PR TITLE
Continue searching for content when an earlier transfer of content fails, or is invalidated

### LINKED ISSUE #1383: Robust RecursiveFindContent | Continue the search if data transfer fails
image

Clients can have bugs, trin has had bugs, shisui has, ultralight etc. A bug in a client shouldn't stop the whole show. A bug we were seeing was trin found the content from a shisui or trin node, then the uTP transfer would fail for some unknown reason, then we would just return an error.

Instead of this we could continue the search until we find a working peer, we already did a big search to find the contents neighbourhood so it isn't out of question if the first node we try to get the data from fails, we just try another and continue the search to some failure level till we either fail X times and give up or successfully fetch the data.

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

Fix #1383 

### How was it fixed?

- send a new message back to the query when the transfer fails, or the validation fails
- resume the search for content when the new message arrives
- expand the existing test to verify that content is eventually found, even if it sometimes is invalid

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] rebase on #1395 
- [x] Clean up commit history and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] make sure follow-up items from #1383 go into new issue(s)

### CODE REVIEW

File: portalnet/src/find/iterators/findcontent.rs [hunk 1]
```diff
@@ -56,15 +56,15 @@ pub enum FindContentQueryPending<TNodeId> {
         // peer that sent the content
         peer: TNodeId,
         // channel used to send back the validated content info
-        valid_content_tx: Sender<ValidatedContent<TNodeId>>,
+        valid_content_tx: Sender<Option<ValidatedContent<TNodeId>>>,
```
Comment (mrferris) [inline portalnet/src/find/iterators/findcontent.rs:59]: We spoke about how to differentiate between a failed utp and failed validation within the trace, and you mentioned it would be tough to send the trace between threads. I think we could instead pass back a wrapper datatype enum here with `ValidatedContent`, `FailedUtp`, and `FailedValidation` variants instead of `None` on failure. 

Not a blocker on this PR.

**Review by mrferris — APPROVED** [review]
